# Generated by Django 4.1.6 on 2023-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='recipient',
            field=models.CharField(default='', max_length=255),
        ),
    ]
